### ISSUE TITLE
Parse quick build pdfs

### ISSUE THREAD

**Issue by therealppa** [guidokessels/xwing-data2#225]
I have written a small script that parses the Quick Builds pdf files and outputs the data in xws format. I see that there are already some quick builds defined here, I'm looking for ideas / interest in merging the resulting data (or maybe even the projects) together. Take a look:

https://github.com/therealppa/xwing-quickbuild-xws

**Comment by sirjorj** [comment]
Nice work!  I have never heard of groove before but in poking through this, i see you calculate the threat based on the point costs?  Does that really work?
The reason I ask is that I have been working on a data comparer (https://gitlab.com/sirjorj/xdv) that compares the data in my c++ based library with xwing-data2 and the ffg pdf files (and yasb is in the works).  To parse the pdf, I use the pfdtotext utility and the parse the text I get from that.  When I tried to do this with the quickbuild pdfs, i discovered that the thread indicator is an image so i could not parse it!  If your sum of points / 25 thing is consistent, you get a gold star for figuring that out!

**Comment by therealppa** [comment]
Groovy is a scripting language kind of similar to Java.

The points / 25 formula works most of the time, I found only 13 entries in all the pdfs where it doesn't fit. My plan is to have a list of exceptions somewhere to manually override them.

These are the exceptions:

expected: 3 has: 2 / 2.48 / 62 (rebel-alliance/btl-a4-y-wing/norra-wexley-ffg1.json)
expected: 3 has: 2 / 2.4 / 60 (rebel-alliance/ut-60d-u-wing/cassian-andor-ffg1.json)
expected: 6 has: 7 / 6.84 / 171 (rebel-alliance/modified-yt-1300-light-freighter/chewbacca-ffg1.json)
expected: 4 has: 5 / 4.52 / 113 (rebel-alliance/yt-2400-light-freighter/leebo-ffg1.json)
expected: 6 has: 5 / 4.52 / 113 (rebel-alliance/vcx-100-light-freighter/chopper-and-ap-5-ffg1.json)
expected: 4 has: 5 / 4.72 / 118 (rebel-alliance/vcx-100-light-freighter/lothal-rebel-and-zeb-orrelios-ffg1.json)
expected: 3 has: 2 / 2.44 / 61 (scum-and-villainy/btl-a4-y-wing/kavil-ffg1.json)
expected: 3 has: 4 / 3.76 / 94 (scum-and-villainy/jumpmaster-5000/dengar-ffg1.json)
expected: 3 has: 4 / 3.52 / 88 (scum-and-villainy/jumpmaster-5000/manaroo-ffg1.json)
expected: 3 has: 4 / 3.84 / 96 (scum-and-villainy/yv-666-light-freighter/latts-razzi-ffg1.json)
expected: 3 has: 2 / 2.48 / 62 (resistance/t-70-x-wing/jessika-pava-ffg1.json)
expected: 4 has: 3 / 3.48 / 87 (resistance/scavenged-yt-1300/resistance-sympathizer-ffg1.json)
expected: 4 has: 3 / 3.48 / 87 (first-order/upsilon-class-shuttle/major-stridan-ffg1.json)

**Comment by therealppa** [comment]
This formula also catches the resistance and first order outliers:

((points / 25) * 1.01).round()

Interestingly, the new empire pdf kind of fixed all threat values to the intuitive formula. I was kind of thinking some of the values had been purposefully corrected in one direction or the other but it looks a bit like they just did not do the calculation very cleanly.

Another aside, this was a bit of a just-for-fun project for me and I guess going forward it's going to be easier to just put in the data manually. Probably not too many new quick builds coming in every upcoming wave. And there is already a PR for the new data.
