### ISSUE TITLE
Non-English Language Support

### ISSUE THREAD

**Issue by J1mBob** [guidokessels/xwing-data2#239]
The official squad builder has support for multiple languages. Is there any way to scrape that data into xwing-data2? If there isn't a clever way to automate this, I'd be happy to manually crunch the other languages into .json files if someone more clever than me can help by suggesting a proper structure for the data to take on.

**Comment by FreakyDug** [comment]
I think this is a good idea and it should definitely be possible to modify the scripts we already have for pulling from the squad builder's API to pull this data as well. 

As for data structure, I think we'd have to leave the english text where it is for backwards compatibility but we could add a parallel key to each text key containing a dictionary with the values for each language (using ISO language codes as the keys).

**Comment by danrs** [comment]
This issue has been inactive for over a year and will be closed if there is no further activity before 15/09/2020.

Note that some translations have been applied in data/translations.json. Further translations could be applied there.
