### ISSUE TITLE
Group Quick Builds by Card

### ISSUE THREAD

**Issue by iwerts** [guidokessels/xwing-data2#273]
Currently, the list of quick builds are not grouped together. Fantasy Flight Games groups the quick builds on cards and these cards appear to have a pattern: 1 or 2 named pilot quick builds followed by a generic pilot quick build. This pattern holds true when viewing the official list of quick builds available on Fantasy Flight's support website for quick builds for products that do not contain quick build cards (such as the faction conversion kits).

I have followed this pattern and created the following Quick Builds list.

https://raw.githubusercontent.com/iwerts/iwerts.github.io/master/xwsquickbuilds.json

**Comment by danrs** [comment]
This issue has been inactive for over a year. I'm going to close it in a week or two if there is no further activity.

Quick builds are currently a low priority for this repo, as there are currently no known users of the quick build content. I also don't see any great value in grouping quick builds to match the FFG cards.
