### ISSUE TITLE
Ordnance icon

### ISSUE THREAD

**Issue by FreakyDug** [guidokessels/xwing-data2#28]
The attack data for upgrades doesn't indicate whether they have the ordnance icon on the card (which means range bonuses don't apply). Currently all Missiles and Torpedos have it and all other special weapons don't, so you can infer it, but that could change.

The question is should it be a `range_bonus` property that is `1` for normal weapons and `0` for Missiles and Torpedoes, or an `ordnance` property that is `0` for other weapons and `1` for Missiles and Torpedoes?

**Comment by DevJonny** [comment]
I think `ordnance: 1` for Missiles and Torps makes the most sense, as it reflects game terminology and mechanics. Then anything without it would be `ordnance: 0` or `ordnance` is not present.

**Comment by elistevens** [comment]
I think that matching what's printed on the card makes sense, since rules can change, but FFG has been reluctant to outright change printed icons.

**Comment by guidokessels** [comment]
As the icon is called `ordnance icon` in the rulebook I think `ordance: <true|false>` makes the most sense.

**Comment by FreakyDug** [comment]
I was leaning the other way, but you all made convincing arguments. I'll put a pull request together.
