### ISSUE TITLE
Quibuilds of Hotshots and Aces reinforcements pack

### ISSUE THREAD

**Issue by Gan0n29** [guidokessels/xwing-data2#348]
Hi,

Can you update quickbuild .json files with those new pilots ?
[https://xwing-miniatures-second-edition.fandom.com/wiki/Hotshots_and_Aces_Reinforcements_Pack](url)

I can scan you the quickbuild cards if you want (in french...)

Thanks.

**Comment by Gan0n29** [comment]
Hi, 

I'm doing the update in my fork.

**Comment by guidokessels** [comment]
@Gan0n29 Great! Please make a PR when you're done so we can merge it back here :)
