### ISSUE TITLE
XWS to Text

### ISSUE THREAD

**Issue by sebald** [guidokessels/xwing-data2#353]
Hey,

is there a lib that converts XWS to text? Looking at the YASB code and https://github.com/guidokessels/xwing-list-loader there only seems to be the other direction available. YASB also seems to have their own [internal format](https://github.com/raithos/raithos.github.io/blob/master/javascripts/xwingcontent.js).

Sorry for asking this here, but this is the best I could find 🙈

Cheers,
Sebastian

**Comment by sirjorj** [comment]
My site has a service that will do some squad conversions: https://xhud.sirjorj.com/xwing.cgi/squad2?

**Comment by sebald** [comment]
@sirjorj that is awesome! I was looking for something that doesn't require async calls. I wrote a small script that transforms all the JSON data the way I need it. Not pretty but works :)

**Comment by sirjorj** [comment]
Glad to help!  If you found that site useful for a project, i would be happy to put a link to your project on the index page.
