### ISSUE TITLE
Some feedback

### ISSUE THREAD

**Issue by FreakyDug** [guidokessels/xwing-data2#4]
I think the new data is looking good so far, but here are a few things that I noticed while looking through it:
- I don't understand the middle letter in the dial specification. What do all the different values mean?
- The format currently can't handle pilots who have a different ship ability to the other pilots with the same ship (Nashtah pup, Autopilot drone). Maybe have a ship_ability_override on the pilot?
- Do we know for sure that there won't be charges or force stats with more than 1 regen per turn? It might be safer to have regenerates be 0 or 1 so it can easily adapt if that does happen.

**Comment by guidokessels** [comment]
@FreakyDug Thanks for the feedback!

Here are the answers to your questions:

1. The dial specification follows Mu0n's [dialgen](http://xwvassal.info/dialgen/dialgen) format. It's 3 characters and always `<speed><maneuver><difficulty>`
2. Yes I think a `shipOverride` field or something similar is the way to go here. The other option would be to get rid of the ship data altogether and repeat the ship information in every pilot. That'd cause a _lot_ of duplication of data though which I'm not really a fan of.
3. I agree with this. It makes it a lot more future-proof. I have already made this change locally but have not push that to Github yet.

Let me know if there's anything else that comes to mind.

**Comment by FreakyDug** [comment]
1. Ah, I hadn't seen that format before. Cool.
2. Agreed, the pattern certainly seems to be a shared ship ability with the occasional exception.
3. 👍
