### ISSUE TITLE
R5-D8 image points to an image of R5-P8

### ISSUE THREAD

**Issue by acosoi** [guidokessels/xwing-data2#46]
The recently added "image" property for R5-D8 points to an image of R5-P8.

I've been looking for a clean image of Second Edition R5-D8 from FFG, but the only one I could find is [this one](https://images-cdn.fantasyflightgames.com/filer_public/20/14/20140e24-53bc-48f9-b4f0-8984938ff737/swz01_a5_charge_diagram.jpg).

[This wiki](http://xwing-miniatures-second-edition.wikia.com/wiki/R5-D8) has a clean image of just the card, but I couldn't find it on FFG's website.

Should I update the image for R5-D8 to point to the FFG image (the one with other elements) or the wiki one (the one with just the card, but with an unknown source)?

**Comment by guidokessels** [comment]
Well spotted! I'll move the image to R5-P8 and use the one from the wiki for R5-D8.

The only source for it that I could find is FFG's article https://www.fantasyflightgames.com/en/news/2018/5/21/take-action-1/:

![R5-D8](https://images-cdn.fantasyflightgames.com/filer_public/20/14/20140e24-53bc-48f9-b4f0-8984938ff737/swz01_a5_charge_diagram.jpg)
