### ISSUE TITLE
Incorrect data

### ISSUE THREAD

**Issue by danrs** [guidokessels/xwing-data2#479]
Kerbocat has found the following errors:
- First Order pilots' name should be in double-quotes like "Scorch" - but are listed as Scorch
- overtunedmodulators is set to limited 1, should be 0
- babufrik is set to limited 0, should be 1

**Comment by danrs** [comment]
Let's leave this up and collate errors so we can fix them all in one go

**Comment by danrs** [comment]
BB-8 cost is wrong, reported by Elred

**Comment by danrs** [comment]
Electro-chaff text is wrong (straight launch template should be speed 4, not 3)

**Comment by SogeMoge** [comment]
Resistance Y-Wing pilot Shasa Zaro has wrong initiative 4 instead of 3
https://xwing-miniatures-second-edition.fandom.com/wiki/Shasa_Zaro

**Comment by danrs** [comment]
DBD-404 has some garbage characters at the start of its name - probably a bad unicode dot

**Comment by danrs** [comment]
Closed - fixed in #480
