### ISSUE TITLE
Thermal Detonators (device.json) is missing a device node

### ISSUE THREAD

**Issue by pakirby1** [guidokessels/xwing-data2#490]
"device" : {
"name" : "Thermal Detonators",
"type" : "Bomb",
"effect" : "At the end of the Activation Phase, this device detonates. When this device detonates, each ship and remote at range 0–1 rolls 1 attack die. Each ship gains 1 strain token for each [Focus] result, and each ship and remote suffers 1 [Hit]/[Crit] damage for each matching result."
}

**Comment by danrs** [comment]
Closed in #500
