### ISSUE TITLE
Data structure for pilots cost with new rules

### ISSUE THREAD

**Issue by RubberChickenParadise** [guidokessels/xwing-data2#503]
Changes are in bold from what would make sense based on the new squad builder restrictions.

For Pilots, there are only a couple of additional fields that are needed.

{
    "name": "Fenn Rau",
    "caption": "Skull Leader",
    "initiative": 6,
    "limited": 1,
    **"cost": 7,
    "loadout":12,**
    "xws": "fennrau",
    "ability": "While you defend or perform an attack, if the attack range is 1, you may roll 1 additional die.",
    "image": "https://sb-cdn.fantasyflightgames.com/card_images/Card_Pilot_155.png",
    "shipAbility": {
      "name": "Concordia Faceoff",
      "text": "While you defend, if the attack range is 1 and you are in the attacker's [Front Arc], change 1 result to an [Evade] result."
    },
    "slots": ["Talent","Talent", "Torpedo","Modification"],
    "artwork": "https://squadbuilder.fantasyflightgames.com/card_art/Card_art_XW_P_155.jpg",
    "ffg": 155,
    **"standard": true,
    "extended": true,**
    "keywords": ["Mandalorian"]
  },

For upgrades, leaving the ability to cost things differently by just setting the cost to be `"cost": { "value": 5 },` on everything would fix things without losing the ability to do dynamic points in the future (if those are brought back.)

**Comment by danrs** [comment]
Looks like a sensible change. In future please use a code block for json to make it easier to read.

This issue can be closed once we fire up a branch with the new changes

**Comment by danrs** [comment]
Addressed in #506
