### ISSUE TITLE
Unneeded -crew suffixes after Wave 11 release

### ISSUE THREAD

**Issue by Kerbocat** [guidokessels/xwing-data2#527]
In https://github.com/guidokessels/xwing-data2/blob/master/data/upgrades/crew.json:

The following have an unneeded -crew suffix:
garsaxon-crew should be garsaxon
captainhark-crew should be captainhark
previzla-crew should be previzla
rookkast-crew should be rookkast

YASB, LBN and PBM are giving/expecting that suffix to not be there, and the removal of the suffix is in line with XWS spec.

**Comment by danrs** [comment]
@J1mBob @Mu0n FYI I am proceeding with this change request

@J1mBob somewhat related: I'm also discussing a change to XWS generation (suggested by raithos) on xwvl slack. Let me know where/how I can contact you to get your thoughts

**Comment by danrs** [comment]
Fixed in #528
