### ISSUE TITLE
What about Syliure-class Hyperspace Ring and TransGelMag Control Link?

### ISSUE THREAD

**Issue by Radroggor** [guidokessels/xwing-data2#549]
Syliure-class Hyperspace Ring is not really a ship but a sort of, with some ships characteristics :

- id (ffg) : 787
- ffg_id : XW_P_428
- agility : 1
- hull  : 1
- shields : 2
- code : SHR

https://xwing-seconde-edition-fr.fandom.com/fr/wiki/Liaison_de_Contr%C3%B4le_TransGalMeg

His "pilot" is "TransGelMag Control Link".

It works for EPIC game. With "hyperdrive" upgrade.

I would like to add theses objects to "\data\pilots\galactic-republic".
Any objections?

**Comment by danrs** [comment]
Fixed in #558
