### ISSUE TITLE
All high-res cards available via FFG website

### ISSUE THREAD

**Issue by acosoi** [guidokessels/xwing-data2#55]
@guidokessels don't know if you've seen it already, but [someone on Reddit](https://www.reddit.com/r/XWingTMG/comments/9fkkyc/download_all_hires_card_images/) found all of the pilot and upgrade cards in high resolution on FFG's CDN.

If you've seen that already or it's not useful, feel free to close this issue. I created it because I couldn't figure out another way to contact users on GitHub :)

**Comment by acosoi** [comment]
Nevermind, just saw the [pull request](https://github.com/guidokessels/xwing-data2/pull/56) with those new asset URLs. Going to close this issue.

**Comment by guidokessels** [comment]
Thanks! I just merged the other PR :)
