### ISSUE TITLE
Incorrect points and loadout for Aggressor Assault Fighters (SCUM IG)

### ISSUE THREAD

**Issue by Dolsha** [guidokessels/xwing-data2#550]
**Current**:
IG-88B cost 6, loadout 13;
IG-88D cost 7, loadout 16.

**Must be**:
IG-88B cost 7, loadout 16;
IG-88D cost 6, loadout 13

_Source_:
Official pdf with pilot points from AMG (10 page):
https://static1.squarespace.com/static/5ce432b1f9d2be000134d8ae/t/6287b7c0f395202572c2281c/1653061568918/SWZ_Ship_Points_062022.pdf
![image](https://user-images.githubusercontent.com/28804651/170463000-cddda49d-7256-4ff6-b22c-78089687e53b.jpeg)

**Comment by danrs** [comment]
Fixed in #557
