### ISSUE TITLE
Update standard expansions to specific tag schema

### ISSUE THREAD

**Issue by raithos** [guidokessels/xwing-data2#560]
I want to make that any pilots from the new expansion battle of yavin and siege of coruscant have the tag -battleofyavin and -siegeofcoruscant respectively for the xws tags, regardless of whether the pilot doesnt exist otherwise. since Hotshots and aces 2 has a non standardized version of pops, id prefer that to keepo things consistant for identifiying ships via xws.

**Comment by danrs** [comment]
I think this is a good idea. Let's do it

**Comment by danrs** [comment]
Closed in #590
