### ISSUE TITLE
Inconsistent quote marks

### ISSUE THREAD

**Issue by danrs** [guidokessels/xwing-data2#566]
Found by @chrisalleng

note for future us, it looks like some quoted names in xws are escaped:
"name": "\"Slider\"",
vs others that are using the quote symbols:
"name": "“Mauler” Mithel"

**Comment by danrs** [comment]
@chrisalleng do you have a preference here? I think quote symbols might be more "correct", and given that they are inside of a string field I'm kindof ok with using them even though I much prefer ascii to unicode

**Comment by chrisalleng** [comment]
I agree, I think the quote symbols are more correct, despite being a bigger headache.

**Comment by danrs** [comment]
Closed in #590
