### ISSUE TITLE
Missing [Shield] translation

### ISSUE THREAD

**Issue by chrisalleng** [guidokessels/xwing-data2#572]
Looks like we do not currently have a [Shield] icon/translation, but the upcoming Durge (Scum) requires it. It's been used in the past as well at least on r2d2-resistance, where it is just "shield" in XWS, but the card icon is a printed shield. Attached examples
![image](https://user-images.githubusercontent.com/3527305/200743752-b074e63a-639b-4179-a7e3-ba2493c89a99.png)
![image](https://user-images.githubusercontent.com/3527305/200743766-978278e1-312c-49bb-8579-5e97b10168e9.png)

**Comment by danrs** [comment]
I think we only need to add it to [keywords.js](https://github.com/guidokessels/xwing-data2/blob/cc9e960e34686965632623c6bb9c192e856e262c/tests/helpers/keywords.js) (based on a search for `[Critical Hit]` across the repo.

**Comment by danrs** [comment]
Looks like it was already in there, so I updated the cards in #577
