### ISSUE TITLE
Actions by ship (and not by pilot) seems to become an issue

### ISSUE THREAD

**Issue by Radroggor** [guidokessels/xwing-data2#593]
For now, actions are linked to ships in json files.

But some pilots have now their own specific actions:
- Kelrodo-Ai: linked action is a red focus (not a red calculate) (because it's a new organic pilot) (seems confirmed by AMG?)
- Agent Tierny: he has a white lock instead a red (confirmed by AMG: https://forums.atomicmassgames.com/topic/8343-tierny-white-lock/)
- Count Dooku (Coruscant): he has additional white jam and red cloak actions
- DBS-32C: has jam instead reload
- DBS-32C (Coruscant): has jam instead reload
- ...

So actions should be defined for each pilot in json files, not only by ship...

To be continued...

**Comment by chrisalleng** [comment]
is there an issue with the shipActions tag some pilots have? For example, SoC DBS32C has:

      "shipActions": [
        { "difficulty": "White", "type": "Calculate" },
        { "difficulty": "White", "type": "Lock" },
        {
          "difficulty": "White",
          "type": "Barrel Roll",
          "linked": { "difficulty": "Red", "type": "Lock" }
        },
        { "difficulty": "Red", "type": "Jam" }
      ],

**Comment by Radroggor** [comment]
Ah ok!

Some pilots have their own "shipActions", like I asked.
So it's fine.
