### ISSUE TITLE
scavenged-yt-1300 should be named scavenged-yt-1300-light-freighter

### ISSUE THREAD

**Issue by Radroggor** [guidokessels/xwing-data2#597]
According to others YT-1300, "Scavenged YT-1300" should be named "Scavenged YT-1300 Light Freighter"

  "name": "Scavenged YT-1300",
  "xws": "scavengedyt1300",

should be

  "name": "Scavenged YT-1300 Light Freighter",
  "xws": "scavengedyt1300lightfreighter",

In AMG's Ship Points Document, name is correct : "Scavenged YT-1300 Light Freighter"

**Comment by danrs** [comment]
I think the AMG points document is the odd one out here. The name "Scavenged YT-1300" is on the [ship card](https://infinitearenas.com/xw2/images/pilots/chewbacca-scavengedyt1300.png) and consequently is used by XWS, YASB, LBN, Infinite Arenas and List Fortress. 

Changing the name and xws now would only cause confusion and be of no added value. I'm also not sure who the "others" you refer to are.
