### ISSUE TITLE
Points values released

### ISSUE THREAD

**Issue by finsterdexter** [guidokessels/xwing-data2#6]
I'm not even sure if you're wanting to add these values in:
https://www.fantasyflightgames.com/en/news/2018/7/27/man-your-ships-1/

If so, I might be able to help out with entering some of this in, as I *might* have some spare time this weekend.

**Comment by guidokessels** [comment]
Yep they'll be added! I'll import them from http://sirjorj.dyndns.org/cgi-bin/xwing.cgi/pilots2?format=json
