### ISSUE TITLE
Why is the `standardLoadout` field not identical to `upgrades`

### ISSUE THREAD

**Issue by pakirby1** [guidokessels/xwing-data2#600]
In `quick-build.schema.json` the upgrades are defined as 

```
"upgrades": {
            "type": "object",
            "additionalProperties": false,
            "patternProperties": {
              "^(astromech|cannon|configuration|crew|device|force-power|gunner|illicit|missile|modification|sensor|tactical-relay|talent|tech|title|torpedo|turret)$": {
                "type": "array",
                "minLength": 1,
                "items": { "type": "string", "pattern": "^[a-z0-9-]+$" }
              }
            }
```
while in the `pilot.schema.json` the standard loadout upgrades are an array of strings.  

```
"standardLoadout": {
      "type": "array",
      "items": {
        "type": "string",
        "pattern": "^[a-z0-9-]+$"
      }
    }
```
I would expect the types to be the same since they both store upgrades.

**Comment by danrs** [comment]
Good point. Chris and I discussed this [here](https://github.com/guidokessels/xwing-data2/pull/561/files/0c07b623e00f67b2d3869e3cb86b7f512ea6b08d..946d1e8d765194d50bd807fc7f7625c0c20ee8e9#r1008661966) when he added the new schema. I didn't think to look in the quick builds file at the time but this looks like a good improvement.

**Comment by danrs** [comment]
Ok, I've had a proper read of the two schemas (above) and what it looks like in the data.

Standard Loadout:
```
      "slots": [
        "Talent",
        "Turret",
        "Torpedo",
        "Astromech",
        "Device",
        "Missile",
        "Modification"
      ],
```

Quick Builds:
```
          "upgrades": {
            "talent": ["experthandling"],
            "crew": ["seasonednavigator"],
            "gunner": ["veterantailgunner"],
            "astromech": ["r3astromech"],
            "modification": ["ablativeplating", "hullupgrade"]
          }
```

The quick builds version is certainly more detailed, but I don't think it adds much value. The important bit (`"pattern": "^[a-z0-9-]+$"`) is the same for both. The upgrade type in the quick build schema can be inferred from the xws id anyway.

The quick build schema is also much more work for those of us doing data input (and there's a potential for error eg if we list a talent as a modification).

If we were to take action on this issue, I'd actually propose simplifying the quick build schema and data to match what we've done on standard loadouts. However, I think quick builds in this repo are rarely used so I don't see much value in doing that.

@chrisalleng may also have an opinion

**Comment by danrs** [comment]
I'll close this if no further activity by Feb

**Comment by chrisalleng** [comment]
Sorry I've been hard to find. Yeah, I think the quick build schema would be the better one to change.

I also agree it's not worth the effort to do so, I suspect it's just making extra work for people, and I don't expect anyone to start some new project with quickbuilds as I suspect they're effectively being quietly sunsetted with the more fleshed out standard loadout cards.
