### ISSUE TITLE
Overturned modulators missing img and artwork - File found

### ISSUE THREAD

**Issue by TripleBlankTriple** [guidokessels/xwing-data2#601]
As said in title, overturned modulators (upgrade, illicit) is missing img and artwork. An official image of the card can be found on the AMG Twitter account.

Here is a link to the tweet: https://twitter.com/atomicmassgames/status/1475497106118955010?s=20&t=5Y_2ABrodGNLM9Qx131dig

**Comment by danrs** [comment]
Thanks Triple. It is preferred to use images hosted on infinite arenas for this project, in this case [https://infinitearenas.com/xw2/images/upgrades/overtunedmodulators.png](https://infinitearenas.com/xw2/images/upgrades/overtunedmodulators.png)

Feel free to create a pull request to add this into the illicits file. You can look at the other cards in that file to see the json for specifying an image
