### ISSUE TITLE
value of "???" for cost fix.

### ISSUE THREAD

**Issue by pakirby1** [guidokessels/xwing-data2#605]
I've noticed that some of the cost fields are set to "???" for the value key.  The cost should be an Int type but it is set to "???".  Why is this and what should the Int value for these fields be set to?

{
    "name": "Delta-7B",
    "limited": 0,
    "xws": "delta7b",
    "sides": [
      {
        "title": "Delta-7B",
        "type": "Configuration",
        "slots": ["Configuration"],
        "grants": [
          { "type": "stat", "value": "agility", "amount": -1 },
          { "type": "stat", "value": "shields", "amount": 2 },
          { "type": "stat", "value": "attack", "arc": "Front Arc", "amount": 1 }
        ],
        "ffg": 548,
        "image": "https://squadbuilder.fantasyflightgames.com/card_images/en/515903e04a0d06a9200860698326896d.png",
        "artwork": "https://squadbuilder.fantasyflightgames.com/card_art/6530f18639b7efff5a5a659589e5d65c.jpg",
        "text": "The Delta-7B was designed as a heavier variant of the Delta-7 Aethersprite-class Interceptor, identifiable by the repositioned astromech slot. Many Jedi Generals favor this craft's greater firepower and durability."
      }
    ],
    "cost": { "value": "???" },
    "restrictions": [{ "ships": ["delta7aethersprite"] }],
    "standard": false,
    "extended": false,
    "epic": false
  },

**Comment by danrs** [comment]
In the case of D7B there's no valid cost as the card is banned, so I guess -1 would make sense. Feel free to raise a PR with this change

**Comment by pakirby1** [comment]
Maybe something other than -1, otherwise people would gain an extra point possibly.  This isn't a big deal, since the squad builders prevent people from using this card.

**Comment by danrs** [comment]
Good point - how about `999`?

**Comment by chrisalleng** [comment]
Seems like a good argument for null as the value? I have the same question for adding the starter set and endor pilots that are in the process of being spoiled.

**Comment by pakirby1** [comment]
The problem is that it should be an int value (not null).

**Comment by pakirby1** [comment]
For my app, the pilot cost is a required Int.  The upgrade cost is a
nullable Int.  I think if we make the pilot cost to be nullable that should
fix the issue.  Consumers of the xws would need to update their apps to
support the nullable field.

**Comment by s1n** [comment]
Cost would be an optional property in that case.

As an alternative, you could separate cost, slots, restrictions, and keywords to separate files denoting the rules of the game format. That is, standard would lack this pilot, even if they have a definition, thereby making them banned in that format. Currently, you have format membership defined as a binary properties. That would separate the information vut give you the ability to define formats, format specification, and rule sets similar to the old FFG squad builder.

**Comment by pakirby1** [comment]
I agree on the optional property.

Is minimizing the impact on the squad builder devs a concern?  Or are they
fairly adept at making changes to their apps based on the XWS definition?

**Comment by chrisalleng** [comment]
I don't think there are any squadbuilders currently using XWS for anything other than import/export functionality, both YASB and LBN have different internals.

@danrs if you're cool with it, I can go ahead and remove the cost on 7B on the giant open PR to save you a versioning update as well

**Comment by danrs** [comment]
Sure, go for it

**Comment by danrs** [comment]
Fixed in #610
