### ISSUE TITLE
force_side stat not supported

### ISSUE THREAD

**Issue by danrs** [guidokessels/xwing-data2#65]
https://squadbuilder.fantasyflightgames.com/api/cards/ shows a force_side stat on all pilots. Presumably, this stat will be used in future to support dark/light side upgrades. 

force_side has the following values:
NULL: no force
1: dark side
2: light side

**Comment by danrs** [comment]
I am happy to take a look at this once I'm done with my quick builds PR.

Actions to be taken:
- add force_side to FFG conversion script
- add force_side to force-sensitive pilots. Proposed format would be as follows (using Vader as an example): `"force": { "value": 3, "recovers": 1, "side": 1 }`

Alternately, we could use `"force": { "value": 3, "recovers": 1, "side": "dark" }` but I don't see much benefit to doing so

**Comment by guidokessels** [comment]
> Presumably, this stat will be used in future to support dark/light side upgrades.

It seems like Maul (crew) already references Dark Side upgrades:

![Maul](https://sb-cdn.fantasyflightgames.com/card_images/Card_Upgrade_136.png)

**Comment by danrs** [comment]
Agreed, Maul indicates that we are probably going to see "dark side" upgrades in the future which can only be equipped on characters with `force_side` = 1. Similarly there will most likely be light side upgrades which you can only equip if you have `force_side` = 2.

Do you have any preference of using numbers (`1` and `2`) or words (`dark` and `light`) in the xws data to represent this value?

**Comment by danrs** [comment]
Closing issue as I've raised a PR for this
