### ISSUE TITLE
Ship data files?

### ISSUE THREAD

**Issue by izakman** [guidokessels/xwing-data2#75]
Hi, wanted to put forward the suggestion to add separate file/s for ship data.

I saw (in https://github.com/guidokessels/xwing-data2/pull/62) that it looks like it's something that isn't wanted at the moment but I think it's important to have. Any tool that wants to get a list of ships currently has to parse all the pilot files.

**Comment by danrs** [comment]
Do you have a specific use case where this would be beneficial? At present I can't see that this will have any great advantages over the current system. Parsing the pilot files isn't a high cost, and if we move the ship data elsewhere then we either have duplicate data (bad) or existing applications will have to change to parse both pilot and ship files (also bad)

**Comment by izakman** [comment]
Not really a specific use case. I've played around with building a squad builders with this and the 1.0 data, and I've always internally split the ship/pilots out. So it's not parsing the JSON as such, but manipulating the data in an app. Having ship data in their own files with an ID in the pilot data seems more flexible to me, coming from more of a relational database kind of mindset.

But I get it might not worth the change at this point.

**Comment by danrs** [comment]
I understand where you're coming from in terms of data separation, as I was expecting separate files for ships/pilots as well when I first read through the data. But as you say there's not much value to be gained from splitting them out at this stage.
