### ISSUE TITLE
Device Effects Data

### ISSUE THREAD

**Issue by davidhorm** [guidokessels/xwing-data2#81]
I suggest storing the effects of device tokens data somewhere. I believe each device token corresponds with one upgrade card, so perhaps add the following to the upgrade.

`{"effect": {"name": "Proximity Mine", "text": "After a ship overlaps..."}}`

Otherwise I could see storing in a separate file.

**Comment by guidokessels** [comment]
Yep, we had this in xwing-data1 and it'd be good to have this again in xwing-data2.

... I really hoped FFG would include the effect on the cards this time instead of putting it on reference cards/booklets :(

**Comment by davidhorm** [comment]
Just realized that the cards from v1 aren't the same :( Welp, a bunch of other things to add to the "safely throw away" pile.

Do you plan on adding this data soon? Or I can help you. I noticed that you put `"effect"` directly on the upgrade card with xwing-data1. But what about the "Rigged Cargo Chute" upgrade that places the "Loose Cargo" token. Would you instead go with the `"effect": {"name": "...", "text": "..."}` format? Or maybe `"token": {"name": "...", "effect": "..."}`?

hmm...if we went with `"token"` would it make sense to break that out into a different file, and add asteroids and debris cloud to the file?

**Comment by davidhorm** [comment]
Completed with https://github.com/guidokessels/xwing-data2/pull/82

**Comment by FreakyDug** [comment]
Thanks for adding this data @davidhorm. I've updated freakydug/r2-d7 to use it. :)
