### ISSUE TITLE
Add Availability data?

### ISSUE THREAD

**Issue by davidhorm** [guidokessels/xwing-data2#83]
Did you want to add Availability data like you would see from http://xwing-miniatures-second-edition.wikia.com/wiki/X-Wing_Miniatures:_Second_Edition_Wiki. I was thinking it would be nice to know which pilots/upgrades are available in certain expansion packs. For example when people ask what's in the Core Set that aren't in the Upgrade Kits.

I'm thinking we can add to the Pilot or Upgrade object. For instance, on the Heightened Perception force upgrade card:

`{ "availability" : [ { "product" : "X-Wing Core Set", "quantity" : 2 } ]}`

And then for the Afterburners modification upgrade card:

`{ "availability" : [ { "product" : "X-Wing Core Set", "quantity" : 1 }, { "product" : "Fang Fighter Expansion Pack ", "quantity" : 1 } ]}`

But I don't know if product should be using some key or id instead.

**Comment by izakman** [comment]
This would be great for squad builders and similar.  You can use the product SKU as an ID.

**Comment by danrs** [comment]
This issue has been inactive for over a year and will be closed if there is no further activity before 15/09/2020.

**Comment by andtrobs** [comment]
I was hoping this functionality would be available. Although I would probably model the data as a product/bundle/expansion entity that lists its components

**Comment by sirjorj** [comment]
I have this info available from my site: https://xhud.sirjorj.com/xwing.cgi/releases2?format=json
