### ISSUE TITLE
Rule Reference

### ISSUE THREAD

**Issue by infinityloop** [guidokessels/xwing-data2#88]
Has anyone attempted to cut up the rule reference and JSONify them? It seems a bit resource intensive and needs to be updated, but it would be very helpful to have on hand for streams if we ever need to quickly reference a rule entry.

**Comment by izakman** [comment]
It would definitely be useful. It would only be bit time consuming the first time. Updates shouldn't happen too often and most of the time it's just a few minor text changes.

**Comment by danrs** [comment]
This issue has been inactive for over a year and will be closed if there is no further activity before 15/09/2020.

If you want to move forward with this issue, I suggest proposing a data structure for storing this information. How would it be organised? How would it be consumed (eg. how would a streamer use it to get a quick reference)?
