### ISSUE TITLE
Auto Sync New Point Costs?

### ISSUE THREAD

**Issue by davidhorm** [guidokessels/xwing-data2#89]
Just saw that new point costs files were uploaded on 2018-10-26. I'm assuming this data needs to be updated still since this repro was last updated 15 days before that. I started manually going through the first handful of ships and didn't notice any changes. Then I thought how there should be an automated way of doing this.

Did you have plan on doing this @guidokessels? I was thinking about writing a node script that'll take the latest info from https://squadbuilder.fantasyflightgames.com/api/cards/ and update the points/slots in the json files. That's assuming the REST data has been updated too. And I might not get to writing this for a couple weeks...

p.s. I just did a diff between my local copy of the REST data, and there were too many changes to see the real difference (because I think they reordered a lot of the data).

EDIT: oh, looks like they didn't actually change any point values or slots with that 2018-10-26 update.

**Comment by izakman** [comment]
I just wrote a js script that checks a card's cost against the api and outputs changes to console (ignores flexible point cost cards though). Maybe something to add to scripts folder? I'll add a pull request when I can.

It did get a hit though when running. Manaroo must have changed from 54 to 56 points at some point...

**Comment by davidhorm** [comment]
Awesome. Looks like the 54 points is a typo that no one caught in xwing-data2. I believe it's a typo because I did archive history on the X-Wing page, and the Point Cost link from July is the same URL as October. And YSAB shows Manaroo at 56 points.

**Comment by danrs** [comment]
Point cost synching has been implemented (`yarn ffgscrape`) so I'm closing this issue
