### ISSUE TITLE
Should shields be 0 instead of absent?

### ISSUE THREAD

**Issue by tprovick** [guidokessels/xwing-data2#98]
After having to build in some special cases to deal with ships without shields, I'm wondering if it would be better to represent ships without shields as having a ship stat of 0 instead of it not being present? Thoughts?

**Comment by FreakyDug** [comment]
I feel that having shields be omitted is better because it matches how attack is implemented (You don't have Turret with value 0 and Rear arc with value 0 on ships with no turret or rear arc) and it sets a better precedent for if they come up with some new stat in the future.

**Comment by tprovick** [comment]
My thinking was that since most 0 shield ships can take Shield Upgrades, starting with a base 0 made sense there in a way that is not true for other occasional stats.

Since I had to build an unanticipated special case into an app consuming this fundamental stat - which I imagine many - I thought it was at least worth bringing it up for discussion.

**Comment by davidhorm** [comment]
I was annoyed by having it omitted, too. But eventually I liked how it matches what's on the card. Decimator has an Agility value of 0, and that's what the data shows. TIE Fighters don't have a shield icon, and the data properly has no shield stats. There's also a ton of ships that don't have Force or Charge values, and I rather those be omitted (or null?) than be 0.

I will say, though, it was annoying trying to figure all the possible values without documentation. I had to merge all the pilot data into a single pilot JSON to figure stuff like ship abilities and conditions.

**Comment by Casenhob** [comment]
I agree with not mentioning it, if it's not on the card.

Maybe you can have the same question for the 'limited' attribute? All generics now have "limited : 0", maybe it can be omitted to indicate they're not limited?
